services:
  - type: web
    name: wastebuddy-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    rootDir: backend
    envVars:
      - key: MONGO_URI
        sync: false          # You will paste this in the Render dashboard
      - key: MONGO_DB
        value: wastebuddy
      - key: PORT
        value: "8080"
      - key: PYTHON_VERSION
        value: "3.11.0"
